# Generated by Django 3.1.5 on 2022-02-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_auto_20220219_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_id', models.CharField(max_length=100)),
                ('available', models.CharField(max_length=100)),
                ('item_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.itemtype')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_manager.location')),
            ],
        ),
    ]
